# DATABASE CONFIGURATION
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/proyecto_covid
spring.datasource.username=root
spring.datasource.password=Soynoob9182
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE CONFIGURATION
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# COVID REPORT CONFIGURATION
covid.report.date=2021-02-01

covid.report.countries=GTM,USA
#covid.report.countries=ALL


app.start.mode=thread
#app.start.mode=query
